// Generated by CoffeeScript 1.7.1
(function() {
  var nbaApp;

  nbaApp = angular.module("nbaApp", []);

  nbaApp.controller('playerController', [
    '$scope', function($scope) {
      return $scope.nbaPlayers = [
        {
          name: 'Kobe Bryant',
          team: 'Lakers'
        }, {
          name: 'LeBron James',
          team: 'Heat'
        }, {
          name: 'Josh Smith',
          team: 'Pistons'
        }, {
          name: 'Joe Johnson',
          team: 'Nets'
        }, {
          name: 'Brandon Jennings',
          team: 'Pistons'
        }, {
          name: 'David Lee',
          team: 'Warriors'
        }, {
          name: 'Norlens Noel',
          team: '76ers'
        }, {
          name: 'Stephen Curry',
          team: 'Warriors'
        }, {
          name: 'Kevin Love',
          team: 'Timberwolves'
        }, {
          name: 'Lavoy Allen',
          team: 'Pacers'
        }
      ];
    }
  ]);

}).call(this);
